FROM node:20.16.0-alpine3.19 AS builder
WORKDIR /app
COPY src/package*.json ./
RUN npm install && npm cache clean --force
ENV PATH=/app/node_modules/.bin:$PATH
COPY src .
EXPOSE 3007
CMD ["npm", "run", "dev"]