version: "3.9"

services:
  client:
    container_name: react-kruw
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3007:3007
    volumes:
      - ./src/src:/app/src
      - /app/node_modules
